version: "3.8"
services:
  app:
    image: node:16-alpine
    container_name: workshop-app
    working_dir: /home/node/app
    volumes:
    - ./:/home/node/app
    ports:
    - "8000:8000"
    command: 
    - npm
    - run
    - dev
